data_sources:
  gpkg:
    type: gpkg
    path: ./data.gpkg

style_variants: [minimal, detailed]

layer_tree:
  - group: all
    defaults:
      scale: {min: 6000000}
      map_themes: [all]
    children:
      - group: infrastructure
        defaults:
          scale: {min: 3000000}
          map_themes: [infrastructure, all]
        children:
          - {vector_layer: populated_places, style: ./styles/populated_places.qml, table: 'populated_places', scale: {max: 1000000}}
          - {vector_layer: roads, style: hidden, style_overrides: {detailed: ./styles/roads.qml}, table: 'roads'}
          - {vector_layer: urban_areas, style: ./styles/urban_areas.qml, table: 'urban_areas', scale: {min: 1000000}}
      - group: water
        defaults:
          style_overrides: {minimal: hidden}
        children:
          - {vector_layer: lakes, style: ./styles/lakes.qml, table: 'lakes'}
          - {vector_layer: lakes_europe, style: ./styles/lakes.qml, table: 'lakes_europe'}
          - {vector_layer: rivers, style: ./styles/rivers.qml, table: 'rivers'}
          - {vector_layer: rivers_europe, style: ./styles/rivers.qml, table: 'rivers_europe'}
      - vector_layer: countries
        style: ./styles/countries.qml
        style_overrides: {minimal: ./styles/countries_gray.qml}
        table: 'countries'
        scale: {min: 0, max: 0}

project_properties:
  WMSServiceCapabilities: true
  WMSServiceTitle: The title of the service
  WMSPrecision: 5
  WMSExtent: ["43547.79", "6522236.87", "764796.72", "7795461.19"]
  WMSMaxAtlasFeatures: 100
  WMSTileBuffer: 100
  crs: 3067


metadata:
  metadata_key_1: value_1
  nested_metadata:
    key_1: value_1
    key_2: value_2
