# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [ pre-commit ]
default_install_hook_types: [ pre-commit, commit-msg ]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [ "pre-commit" ]
      - id: end-of-file-fixer
        stages: [ "pre-commit" ]
      - id: mixed-line-ending
        name: LF for all files
        args: [ --fix=lf ]
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [ --assume-in-merge ]
      - id: check-xml
      - id: debug-statements

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: e72a3ca1632f0b11a07d171449fe447a7ff6795e  # frozen: v0.48.0
    hooks:
      - id: markdownlint
        args: [ "--fix" ]
  # TOML formatter
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: ade0f95ddcf661c697d4670d2cfcbe95d0048a0a  # frozen: v0.9.3
    hooks:
      - id: taplo-format
  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e  # frozen: v8.30.1
    hooks:
      - id: gitleaks
  # Insert copyright header
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8  # frozen: v1.5.6
    hooks:
      - id: insert-license
        name: insert copyright header
        files: \.py$
        args:
          - --license-filepath
          - .copyright-header.txt
          - --use-current-year
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 6fec9b7edb08fd9989088709d864a7826dc74e80  # frozen: v0.15.12
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --extend-fixable=F401 ]
      - id: ruff-format
  - repo: https://github.com/PyCQA/flake8
    rev: c48217e1fc006c2dddd14df54e83b67da15de5cd  # frozen: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-qgis==2.0.1
          - flake8-pyproject==1.2.4
          - flake8-spellcheck==0.28.0
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: fc0f09a29bb495f4a91f00266155d6282d52485d  # frozen: v1.20.2
    hooks:
      - id: mypy
        files: ^src
        additional_dependencies:
          - types-requests
  - repo: https://github.com/adrienverge/yamllint.git
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: [ --strict, -c=.yamllint ]
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint

  # commit-msg hooks
  # Commit messages should follow [Conventional Commits notation](https://www.conventionalcommits.org/en/v1.0.0/#summary).
  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98  # frozen: v0.19.1
    hooks:
      - id: gitlint
        stages: [ commit-msg ]
