# Copyright (C) 2026 QGIS Project Configurator Contributors.
#
#
# This file is part of QGIS Project Configurator.
#
# QGIS Project Configurator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# QGIS Project Configurator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with QGIS Project Configurator.  If not, see <https://www.gnu.org/licenses/>.

"""Generate the JSON Schema and the reference docs of the config format.

The source is `qgis_project_configurator.config_format`. Pydantic is a dev
dependency only, so this script is not part of the package.

Usage:
    uv run python scripts/generate_config_docs.py          # write the files
    uv run python scripts/generate_config_docs.py --check  # fail if outdated
"""

import argparse
import ast
import functools
import inspect
import itertools
import json
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any, TypeAliasType, is_typeddict

from pydantic import TypeAdapter
from typing_extensions import NoExtraItems

from qgis_project_configurator import config_format
from qgis_project_configurator.config_format import MAIN_SCHEMA_URL

ROOT_DIR = Path(__file__).parent.parent
SCHEMA_FILE = ROOT_DIR / "schema" / "config.schema.json"
REFERENCE_FILE = ROOT_DIR / "docs" / "configuration-reference.md"

JSON_SCHEMA_DIALECT = "https://json-schema.org/draft/2020-12/schema"


@functools.cache
def config_type_adapter() -> TypeAdapter[config_format.ProjectConfig]:
    """Return a validator for a loaded config. Unknown keys are errors.

    Sets `__pydantic_config__` on the TypedDicts of `config_format`. Only this
    script and the tests import that module.
    """
    for value in vars(config_format).values():
        if not is_typeddict(value):
            continue
        if getattr(value, "__extra_items__", NoExtraItems) is NoExtraItems:
            value.__pydantic_config__ = {"extra": "forbid"}
        else:
            # extra_items gives the type of the other keys. Do not inherit forbid.
            value.__pydantic_config__ = {}
    return TypeAdapter(config_format.ProjectConfig)


def build_schema() -> dict[str, Any]:
    """Return the JSON Schema of the config format, with field descriptions."""
    schema = config_type_adapter().json_schema()
    definitions = schema.pop("$defs", {})
    class_docs, alias_docs = _read_docstrings()

    for name, definition in [*definitions.items(), ("ProjectConfig", schema)]:
        source = getattr(config_format, name)
        if is_typeddict(source):
            field_docs = _field_docs(source, class_docs)
            for key, field in definition["properties"].items():
                if key in field_docs:
                    field["description"] = field_docs[key]
            # Required keys first: inherited fields would put them last
            required = definition.get("required", [])
            definition["properties"] = dict(
                sorted(
                    definition["properties"].items(),
                    key=lambda item: item[0] not in required,
                )
            )
        elif isinstance(source, TypeAliasType) and name in alias_docs:
            definition["description"] = alias_docs[name]

    return {
        "$schema": JSON_SCHEMA_DIALECT,
        "$id": MAIN_SCHEMA_URL,
        **schema,
        "$defs": {name: definitions[name] for name in _ref_order(schema, definitions)},
    }


def render_reference(schema: dict[str, Any]) -> str:
    """Return the Markdown reference docs for a schema from `build_schema`."""
    definitions = schema["$defs"]
    lines = [
        "<!-- markdownlint-disable MD013 -->",
        "<!-- Generated by scripts/generate_config_docs.py. Do not edit. -->",
        "",
        "# Configuration reference",
        "",
        "Every key of the configuration file. See [the guide](./configuration.md)",
        "for how the keys work together.",
        "",
    ]
    for name, definition in [
        (schema["title"], schema),
        *((name, definitions[name]) for name in definitions),
    ]:
        lines += [f"## {name}", ""]
        if description := definition.get("description"):
            lines += [description, ""]
        if "properties" in definition:
            required = set(definition.get("required", []))
            lines += [
                "| Key | Type | Required | Description |",
                "| --- | --- | --- | --- |",
            ]
            lines += [
                f"| `{key}` | {_type_text(field)} | "
                f"{'yes' if key in required else 'no'} | "
                f"{_table_cell(field.get('description', ''))} |"
                for key, field in definition["properties"].items()
            ]
            lines.append("")
            if isinstance(other := definition.get("additionalProperties"), dict):
                lines += [f"Other keys: {_type_text(other)}", ""]
        else:
            lines += [f"Type: {_type_text(definition)}", ""]
    return "\n".join(lines)


def _read_docstrings() -> tuple[dict[str, dict[str, str]], dict[str, str]]:
    """Read attribute docstrings of the classes and type aliases."""
    module = ast.parse(inspect.getsource(config_format))
    class_docs = {
        node.name: _attribute_docstrings(node)
        for node in module.body
        if isinstance(node, ast.ClassDef)
    }
    return class_docs, _attribute_docstrings(module)


def _attribute_docstrings(node: ast.ClassDef | ast.Module) -> dict[str, str]:
    docs = {}
    for statement, next_statement in itertools.pairwise(node.body):
        match statement:
            case (
                ast.AnnAssign(target=ast.Name(id=name))
                | ast.TypeAlias(name=ast.Name(id=name))
            ):
                pass
            case _:
                continue
        match next_statement:
            case ast.Expr(value=ast.Constant(value=str(docstring))):
                docs[name] = inspect.cleandoc(docstring)
    return docs


def _field_docs(cls: type, class_docs: dict[str, dict[str, str]]) -> dict[str, str]:
    """Field docstrings of a TypedDict, including fields of its TypedDict bases."""
    docs: dict[str, str] = {}
    for base in getattr(cls, "__orig_bases__", ()):
        if is_typeddict(base):
            docs |= _field_docs(base, class_docs)
    return docs | class_docs.get(cls.__name__, {})


def _ref_order(schema: dict[str, Any], definitions: dict[str, Any]) -> list[str]:
    """Definition names in the order they are first used, starting from the root."""
    order: list[str] = []

    def visit(node: Any) -> None:  # noqa: ANN401
        for name in _refs(node):
            if name not in order:
                order.append(name)
                visit(definitions[name])

    visit(schema)
    return order


def _refs(node: Any) -> Iterator[str]:  # noqa: ANN401
    if isinstance(node, dict):
        if ref := node.get("$ref"):
            yield ref.removeprefix("#/$defs/")
        for value in node.values():
            yield from _refs(value)
    elif isinstance(node, list):
        for value in node:
            yield from _refs(value)


def _type_text(node: dict[str, Any]) -> str:  # noqa: PLR0911
    """Return a short Markdown description of a schema type."""
    if ref := node.get("$ref"):
        name = ref.removeprefix("#/$defs/")
        return f"[{name}](#{name.lower()})"
    if "const" in node:
        return f"`{node['const']}`"
    if "enum" in node:
        return " or ".join(f"`{value}`" for value in node["enum"])
    if "anyOf" in node:
        return " or ".join(_type_text(option) for option in node["anyOf"])
    match node.get("type"):
        case "array":
            return f"list of {_type_text(node['items'])}"
        case "object":
            values = node.get("additionalProperties")
            if isinstance(values, dict):
                return f"mapping of {_type_text(values)}"
            return "mapping"
        case str(type_name):
            return type_name
    return "any"


def _table_cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def generate_outputs() -> dict[Path, str]:
    """Return the text of each generated file."""
    schema = build_schema()
    return {
        SCHEMA_FILE: json.dumps(schema, indent=2, ensure_ascii=False) + "\n",
        REFERENCE_FILE: render_reference(schema),
    }


def main() -> int:
    """Write the generated files, or check them with --check."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write. Exit with 1 if the files are not up to date.",
    )
    args = parser.parse_args()

    outputs = generate_outputs()
    outdated = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if args.check:
        for path in outdated:
            print(f"Not up to date: {path.relative_to(ROOT_DIR)}")
        if outdated:
            print("Run: uv run python scripts/generate_config_docs.py")
        return 1 if outdated else 0

    for path in outdated:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(outputs[path], encoding="utf-8", newline="\n")
        print(f"Wrote {path.relative_to(ROOT_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
